### ISSUE TITLE
Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by cikichen** [yonat/RadioGroup#23] opened 2021-12-24 08:04 UTC
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600001f93d90 RadioGroup.RadioGroup:0x7fa74196d5c0.height == 0>",
    "<NSLayoutConstraint:0x600001f8c960 UIStackView:0x7fa74196d7d0.topMargin == RadioGroup.RadioGroup:0x7fa74196d5c0.topMargin>",
    "<NSLayoutConstraint:0x600001f8ca00 UIStackView:0x7fa74196d7d0.bottomMargin == RadioGroup.RadioGroup:0x7fa74196d5c0.bottomMargin>",
    "<NSLayoutConstraint:0x600001f8c730 UIStackView:0x7fa74196d7d0.bottom == UILayoutGuide:0x600000562e60.bottom>",
    "<NSLayoutConstraint:0x600001f8c870 RadioGroup.RadioGroup:0x7fa74196d5c0.bottom == UILayoutGuide:0x600000563100.bottom + 8>",
    "<NSLayoutConstraint:0x600001f8c690 UILayoutGuide:0x600000562e60.top == UIStackView:0x7fa74196d7d0.top>",
    "<NSLayoutConstraint:0x600001f8c7d0 UILayoutGuide:0x600000563100.top == RadioGroup.RadioGroup:0x7fa74196d5c0.top + 8>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001f8c730 UIStackView:0x7fa74196d7d0.bottom == UILayoutGuide:0x600000562e60.bottom>
```

**Comment by yonat** [comment] 2021-12-24 08:22
Duplicate of #16

**Closed as completed by yonat** 2021-12-24 08:22 UTC
Labels: bug
